const { withDangerousMod } = require('@expo/config-plugins');
const path = require('path');
const fs = require('fs');

const PATCH_MARKER = '# [withFollyFix] applied';

const POST_INSTALL_PATCH = `
    ${PATCH_MARKER}
    # Force C++20 on every pod target so folly coroutine headers compile
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
      end
    end
    # Create the missing folly/coro/Coroutine.h stub required by ReactNativeDependencies
    require 'fileutils'
    folly_coro_dir = "#{installer.sandbox.root}/Headers/Public/ReactNativeDependencies/folly/coro"
    FileUtils.mkdir_p(folly_coro_dir)
    coroutine_stub = "#{folly_coro_dir}/Coroutine.h"
    unless File.exist?(coroutine_stub)
      File.write(coroutine_stub, <<~STUB
        // stub generated by withFollyFix config plugin
        #pragma once
        #if defined(__cpp_coroutines) || defined(__cpp_impl_coroutine)
        #include <coroutine>
        namespace folly { namespace coro {
          using coroutine_handle = std::coroutine_handle<>;
          template <typename P = void> using coroutine_handle_t = std::coroutine_handle<P>;
          using suspend_always = std::suspend_always;
          using suspend_never  = std::suspend_never;
        } }
        #endif
      STUB
      )
    end`;

const withFollyFix = (config) =>
  withDangerousMod(config, [
    'ios',
    (config) => {
      const podfilePath = path.join(
        config.modRequest.platformProjectRoot,
        'Podfile',
      );
      let podfile = fs.readFileSync(podfilePath, 'utf-8');

      if (podfile.includes(PATCH_MARKER)) {
        return config; // already patched
      }

      podfile = podfile.replace(
        /(\s*post_install do \|installer\|)/,
        `$1${POST_INSTALL_PATCH}`,
      );

      fs.writeFileSync(podfilePath, podfile);
      return config;
    },
  ]);

module.exports = withFollyFix;
